#default card properties
numofCards = 3
#Card Name Template #1
cardID = 1
color = red
points = 1
blackCost = 1
whiteCost = 0
redCost = 0
blueCost = 0
greenCost = 0
#Card Name Template #2
cardID = 2
color = red
points = 1
blackCost = 1
whiteCost = 0
redCost = 0
blueCost = 0
greenCost = 0
#Card Name Template #3
cardID = 3
color = red
points = 1
blackCost = 1
whiteCost = 0
redCost = 0
blueCost = 0
greenCost = 0
