#the Number of players
#Default value is 2
numOfPlayers = 2
#Number of prestige points to win
#Default value is 15
prestigePointsToWin = 15
#default token is 7
#n = 2
blueToken = 4
redToken = 4
whiteToken = 4
blueToken = 4
blackToken = 4
goldToken = 5
#need a properties file to extract the properties
#cardProperties 
cardPath = card.properties
