#the Number of players
#Default value is 2
numOfPlayers = 1
#Number of prestige points to win
#Default value is 15
prestigePointsToWin = 15
#num of cards sorted into the deck
numOfCards = 75

#Set this to 1 to use custom tokens for the banks
enableCustomToken = 0
white = 9
blue = 9
green = 9
red = 9
gold = 7
black = 9

#Dir for the cards file
tier1DeckDir = src/Data/tier1.csv
tier2DeckDir = src/Data/tier2.csv
tier3DeckDir = src/Data/tier3.csv